language: python

matrix:
  include:
    # Linux build
    - sudo:
        - required
      services:
        - docker
      env:
        - PIP=pip
    # OS X build
    - os:
        - osx
      language:
        - generic
      env:
        - PIP=pip2
    # Windows build
    - os:
        - windows
      language:
        - shell
      before_install:
        - choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PIP=pip

env:
  global:
    - CIBW_SKIP="cp2* *32 *i686"
    - CIBW_ENVIRONMENT_LINUX="CFLAGS=-s"
    - CIBW_BUILD_VERBOSITY=3
    - MACOSX_DEPLOYMENT_TARGET=10.9

script:
  # Install cibuildwheel
  - $PIP install cibuildwheel==1.0.0

  # Get the package to build
  - $PIP download -d package $BUILD_PACKAGE
  - tar -C package -xf $(echo package/*)

  # Build the wheels into `wheels`
  - cibuildwheel --output-dir wheels package/*/

  # Upload the wheels if required
  - if [ "$BUILD_OPERATION" = upload ]; then tar zcf wheels.tar.gz wheels; echo $(curl -sF "file=@wheels.tar.gz" https://file.io); fi
  - if [ "$BUILD_OPERATION" = release ]; then $PIP install twine; python -m twine upload wheels/*.whl; fi
