language: python

matrix:
  include:
    # Linux build
    - sudo:
        - required
      services:
        - docker
      env:
        - PIP=pip
    # OS X build
    - os:
        - osx
      language:
        - generic
      env:
        - PIP=pip2
    # Windows build
    - os:
        - windows
      language:
        - shell
      before_install:
        - choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PIP=pip

script:
  # Install cibuildwheel
  - $PIP install cibuildwheel==1.0.0

  # Get the package to build
  - $PIP download -d package ufal.udpipe==1.2.0.3
  - tar -C package xf $(echo package/*)

  # Build the wheels into `wheels`
  - cibuildwheel --output-dir wheels package/*/

  # Upload the wheels
  - tar Jcf wheels.tar.xz wheels
  - echo $(curl -sF "file=@wheels.tar.xz" https://file.io)
